### ISSUE TITLE
Using template files

### ISSUE THREAD

**Issue by bucky8698** [aquibm/react-liquid#21]
I was hoping to make use of template files to be able to re-use Liquid template code.  I haven't had any luck in locating an example of doing so with the ReactLiquid component.  For example, I'd like to be able to include the following in the template value that I supply to the ReactLiquid component:

```
<ReactLiquid 
    template={"{% render "template" %}"} 
    data={myData}
/>
```
where "template" refers to a file named "template.liquid" that contains Liquid template code (such as a for loop, etc).  Is this possible?  I'm aware that if can be done with Liquid itself.  Thanks in advance!

**Comment by aquibm** [comment]
Hi @bucky8698, yes this is possible. You'll need to make sure that your templates are accessible from the web and be aware that these will be loaded from the sevrer **during** render which might not perform as well as you expect. As far as I know, there's no way to bundle them in with your app.

If you're using `create-react-app`, you can add the templates or partials anywhere under the `public` folder. You should then be able to use the files in your app by supplying `{% include 'path/to/partial.liquid' %}` to the template prop.

**Comment by bucky8698** [comment]
Thanks @aquibm, that worked for me.

More detail in case others want to implement a similar solution.
1.  I created a "liquid" folder under my "public" folder and placed my .liquid file(s) there.
2.  The include statement looked as follows: `{% include '/liquid/myfile.liquid' %}`.
