### ISSUE TITLE
can I add Plugin API like 'antd' to use 'antd component

### ISSUE THREAD

**Issue by crazytrau** [aquibm/react-liquid#3]
https://github.com/harttle/liquidjs#plugin-api

I expect have some thing like  **engine.plugin(require('antd'));**
**Ex**

![image](https://user-images.githubusercontent.com/13588794/57126723-24c7e180-6db8-11e9-92f2-0cac71a90bcb.png)
First one is react com, another is html code I get from browser. But both not working
const template = `
            <DatePicker/>
            <span class="ant-calendar-picker"><div><input readonly="" placeholder="Select date" class="ant-calendar-picker-input ant-input" value=""><i aria-label="icon: calendar" class="anticon anticon-calendar ant-calendar-picker-icon"><svg viewBox="64 64 896 896" class="" data-icon="calendar" width="1em" height="1em" fill="currentColor" aria-hidden="true"><path d="M880 184H712v-64c0-4.4-3.6-8-8-8h-56c-4.4 0-8 3.6-8 8v64H384v-64c0-4.4-3.6-8-8-8h-56c-4.4 0-8 3.6-8 8v64H144c-17.7 0-32 14.3-32 32v664c0 17.7 14.3 32 32 32h736c17.7 0 32-14.3 32-32V216c0-17.7-14.3-32-32-32zm-40 656H184V460h656v380zM184 392V256h128v48c0 4.4 3.6 8 8 8h56c4.4 0 8-3.6 8-8v-48h256v48c0 4.4 3.6 8 8 8h56c4.4 0 8-3.6 8-8v-48h128v136H184z"></path></svg></i></div></span>
        ` 
`return <ReactLiquid template={template}/>`

**Comment by aquibm** [comment]
Heya,

It doesn't look like your template has any liquidJS substitutions? What are you trying to achieve with this component?
